# Generated by Django 5.0.2 on 2024-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_activities_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='dates',
            field=models.DateField(),
        ),
    ]
