# Generated by Django 5.0.2 on 2024-08-31 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_remark_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='admin_remark',
            field=models.CharField(max_length=255),
        ),
    ]
