# Generated by Django 5.0.2 on 2024-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_admin_remark_date_alter_ticket_admin_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadLine',
            field=models.DateField(max_length=255),
        ),
    ]
